### PR TITLE
fix: paused consumers send heartbeats

### LINKED ISSUE #111: fix: paused consumers are triggering partition rebalance
### Expected behaviour
Paused consumers should not trigger a partition rebalance process after poll interval timeout

### Current behaviour
Paused consumers are triggering partition rebalance process after poll interval timeout

### Propsed solution
Consumers should internally call Consume() method, even when it is paused

### PR DESCRIPTION
**Pull request by filipeesch**
# Description

Creates a background Task to send heartbeats to Kafka when the entire consumer is paused

Fixes #111 

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [ ] I have added tests to cover my changes
-   [ ] I have made corresponding changes to the documentation

### Disclaimer

By sending us your contributions, you are agreeing that your contribution is made subject to the terms of our [Contributor Ownership Statement](https://github.com/Farfetch/.github/blob/master/COS.md)

### CODE REVIEW

File: src/KafkaFlow/Consumers/KafkaConsumerFlowManager.cs [hunk 1]
```diff
@@ -0,0 +1,109 @@
...
+        public void Resume(IReadOnlyCollection<TopicPartition> topicPartitions)
+        {
+            lock (this.paused)
+            {
+                if (!topicPartitions.Any())
+                {
+                    return;
+                }
+
+                if (this.heartbeatTokenSource != null)
```
Comment (dougolima) [inline src/KafkaFlow/Consumers/KafkaConsumerFlowManager.cs:84]: I think it should validate if at least one partition was resumed before kill the heartbeat thread. 
Otherwise, if someone tried to resume invalid partitions the heartbeat thread will be cancelled (and it shouldn't).

**Review by dougolima — CHANGES_REQUESTED** [review]

File: src/KafkaFlow/Consumers/KafkaConsumerFlowManager.cs [hunk 2]
```diff
@@ -0,0 +1,109 @@
...
+                            this.consumer.Consume(this.heartbeatTokenSource.Token);
+                        }
+                        catch (OperationCanceledException)
+                        {
+                            // Do nothing
+                        }
+                        catch (Exception ex)
+                        {
+                            this.logHandler.Error(
+                                "Error executing consumer heartbeat",
```
Comment (dougolima) [inline src/KafkaFlow/Consumers/KafkaConsumerFlowManager.cs:66]: There is no producer heartbeat, maybe just `Error executing heartbeat` or `Error executing heartbeat thread` or `Error executing heartbeat background thread` could fit better.

File: src/KafkaFlow/Consumers/KafkaConsumerFlowManager.cs [hunk 3]
```diff
@@ -0,0 +1,109 @@
...
+            ILogHandler logHandler)
+        {
+            this.consumer = consumer;
+            this.stopCancellationToken = stopCancellationToken;
+            this.logHandler = logHandler;
+        }
+
+        public void Pause(IReadOnlyCollection<TopicPartition> topicPartitions)
+        {
+            lock (this.paused)
```
Comment (dougolima) [inline src/KafkaFlow/Consumers/KafkaConsumerFlowManager.cs:33]: What do you think about to rename to pausedPartitions?

File: src/KafkaFlow/Consumers/KafkaConsumerFlowManager.cs [hunk 4]
```diff
@@ -0,0 +1,109 @@
...
+
+                if (!topicPartitions.Any())
+                {
+                    return;
+                }
+
+                this.consumer.Pause(topicPartitions);
+                this.paused.AddRange(topicPartitions);
+
+                if (!this.AreAllPartitionsPaused())
```
Comment (dougolima) [inline src/KafkaFlow/Consumers/KafkaConsumerFlowManager.cs:45]: I think would be more readable if we change to `HasUnpausedPartition` and return in case of true.

**Review by dougolima — CHANGES_REQUESTED** [review]

File: src/KafkaFlow/Consumers/KafkaConsumerFlowManager.cs (hunk 4 above)
Comment (filipeesch) [reply src/KafkaFlow/Consumers/KafkaConsumerFlowManager.cs]: changed to `HasRunningPartitions()`

File: src/KafkaFlow/Consumers/KafkaConsumerFlowManager.cs (hunk 3 above)
Comment (filipeesch) [reply src/KafkaFlow/Consumers/KafkaConsumerFlowManager.cs]: I think it is better too

File: src/KafkaFlow/Consumers/KafkaConsumerFlowManager.cs (hunk 2 above)
Comment (filipeesch) [reply src/KafkaFlow/Consumers/KafkaConsumerFlowManager.cs]: changed to "Error executing paused consumer background heartbeat". What do you think?

File: src/KafkaFlow/Consumers/KafkaConsumerFlowManager.cs (hunk 1 above)
Comment (filipeesch) [reply src/KafkaFlow/Consumers/KafkaConsumerFlowManager.cs]: You are right, validation added

File: src/KafkaFlow/Producers/BatchProduceExtension.cs [hunk 5]
```diff
@@ -118,10 +118,17 @@ public class BatchProduceItem
         }
     }
 
+    /// <summary>
+    /// </summary>
```
Comment (dougolima) [inline src/KafkaFlow/Producers/BatchProduceExtension.cs:122]: Missing documentation on public class.

File: src/KafkaFlow/Consumers/KafkaConsumerFlowManager.cs [hunk 6]
```diff
@@ -0,0 +1,116 @@
...
+                this.heartbeatTokenSource = CancellationTokenSource.CreateLinkedTokenSource(this.stopCancellationToken);
+
+                this.heartbeatTask = Task.Run(
+                    () =>
+                    {
+                        try
+                        {
+                            while (!this.heartbeatTokenSource.IsCancellationRequested)
+                            {
+                                var result = this.consumer.Consume(1000);
```
Comment (dougolima) [inline src/KafkaFlow/Consumers/KafkaConsumerFlowManager.cs:59]: Why this timeout? 
I guess it should block undefinitely, dont you think?

Comment (dougolima) [reply src/KafkaFlow/Consumers/KafkaConsumerFlowManager.cs:59]: I mean, undefinitely = until the task IS cancelled by `Resume`.

File: src/KafkaFlow/Producers/BatchProduceExtension.cs (hunk 5 above)
Comment (filipeesch) [reply src/KafkaFlow/Producers/BatchProduceExtension.cs:123]: Added 😃

File: src/KafkaFlow/Consumers/KafkaConsumerFlowManager.cs (hunk 6 above)
Comment (filipeesch) [reply src/KafkaFlow/Consumers/KafkaConsumerFlowManager.cs]: In this case, the Consume() call will wait until this time expires. If we put a smaller value we will put some unnecessary load on  Kafka brokers, if we put a greater value we will increase the time that Resume() will block the execution. I put the `1000` in a `const int` to name it

**Review by dougolima — APPROVED** [review]
