### PR TITLE
DI bug fixes and better producer recover

### LINKED ISSUE #79: IProducerAccessor is overridden when there are multiple clusters
When we have multiple Kafka clusters the IProducerAccessor is overridden and it returns only the registered producers on the latest configurated cluster.

```csharp
 public ClusterConfiguration Build(KafkaConfiguration kafkaConfiguration)
        {
            var configuration = new ClusterConfiguration(
                kafkaConfiguration,
                this.brokers.ToList());

            configuration.AddProducers(this.producers.Select(x => x.Build(configuration)));
            configuration.AddConsumers(this.consumers.Select(x => x.Build(configuration)));

            this.DependencyConfigurator.AddSingleton<IProducerAccessor>(
                resolver => new ProducerAccessor(
                    configuration.Producers.Select(producer => new MessageProducer(resolver, producer))));

            return configuration;
        }
```

### PR DESCRIPTION
**Pull request by filipeesch**
Closes #79

### CODE REVIEW

File: src/KafkaFlow.Compressor/ConfigurationBuilderExtensions.cs [hunk 1]
```diff
@@ -28,21 +28,17 @@ public static class ConfigurationBuilderExtensions
             Factory<T> factory)
             where T : class, IMessageCompressor
         {
-            middlewares.DependencyConfigurator.AddSingleton<IMessageCompressor, T>();
-            middlewares.DependencyConfigurator.AddSingleton<T>();
```
Comment (tvdias) [inline src/KafkaFlow.Compressor/ConfigurationBuilderExtensions.cs:32]: Is that on purpose?

**Review by tvdias — APPROVED** [review]
